DROP TABLE AppLog;
DROP SEQUENCE AppLogSequence;
CREATE TABLE AppLog (
  id        BIGINT PRIMARY KEY NOT NULL,
  message   CHARACTER VARYING(2048),
  createdBy CHARACTER VARYING(100),
  createdAt TIMESTAMP
);
CREATE SEQUENCE AppLogSequence;
